version: 2.1
jobs:
  Setup Directory:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  Run Unit Tests:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: Run Jest
          command: npm test
  Test Build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: dependency_cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build Project
          command: CI=false npm run build
  Deploy App:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: Build Project
          command: CI=false npm run build
      - run: 
          name: Deploy to Google Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  Test and Deploy:
    jobs:
      - Setup Directory
      - Run Unit Tests:
          requires:
            - Setup Directory
          filters:
            branches:
              ignore: master
      - Test Build:
          requires:
            - Run Unit Tests
          filters:
            branches:
              ignore: master
      - Deploy App:
          requires:
            - Setup Directory
          filters:
            branches:
              only: master