const colorVariables = [
  '--illustration-darkPurple',
  '--illustration-purple',
  '--illustration-chocolate',
  '--illustration-lightTurquoise',
  '--illustration-skyBlue',
  '--illustration-turquoise',
  '--illustration-dustPink',
  '--illustration-brightOrange',
  '--tangerine-30',
  '--blue-10',
  '--blue-20',
  '--blue-30',
  '--blue-40',
  '--blue-50',
  '--indigo-10',
  '--indigo-20',
  '--indigo-30',
  '--indigo-40',
  '--indigo-50',
  '--yellow-10',
  '--yellow-20',
  '--yellow-30',
  '--yellow-40',
  '--yellow-50',
  '--green-10',
  '--green-20',
  '--green-30',
  '--green-40',
  '--green-50',
  '--tangerine-10',
  '--tangerine-20',
  '--tangerine-30',
  '--tangerine-40',
  '--tangerine-50'
]

export default colorVariables
